validation: sovereign
version: 1
build:
  binary: stocd
  proto:
    path: ""
accounts:
- name: admin
  coins:
  - 9000000000ustoc
  mnemonic: hotel deal eagle vast sight treat caught away hidden turkey require crunch beef shield patient blouse marble border awkward enemy uncover canal chicken autumn
- name: dev1
  coins:
  - 500000000ustoc
  mnemonic: unfair pave wet local syrup mention east arctic tribe evil butter diagram into skill pet divert silk intact absurd save furnace raven very fabric
- name: dev2
  coins:
  - 490000000ustoc
  mnemonic: radio post taxi federal win receive sign embrace junk street adapt when practice scrap pen broken donkey gown crew brisk twin record pelican large
faucet:
  name: dev1
  coins:
  - 10000000ustoc
  mnemonic: survey torch diagram asset degree iron diagram torch trophy setup flush
  openapi:
    path: docs/static/openapi.yml
genesis:
  app_state:
    crisis:
      constant_fee:
        denom: ustoc
    staking:
      params:
        bond_denom: ustoc
validators:
- name: dev2
  bonded: 80000000ustoc
  app:
    minimum-gas-prices: 0.0001ustoc

