version: 1
build:
  binary: "stocchaind"
validation: sovereign
genesis:
  app_state:
    staking:
      params:
        bond_denom: "ustoc"
accounts:
- name: admin
  coins:
  - 10000000000000ustoc # 10 billion STOC
- name: alice
  coins:
  - 300000000ustoc     # 300 STOC
- name: bob
  coins:
  - 200000000ustoc  # 200 STOC
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
  - 10100000ustoc      # 101 STOC
validators:
- name: alice
  bonded: 100000000ustoc     # 100 STOC
- name: validator1
  bonded: 100000000ustoc     # 100 STOC
- name: validator2
  bonded: 200000000ustoc     # 200 STOC
- name: validator3
  bonded: 300000000ustoc     # 300 STOC